name: Poster Upload Workflow

on:
  push:
    branches:
      - main  

jobs:
  say-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display success message
        run: echo "Poster Uploaded Successfully"
